"""Add connection between insight and job

Revision ID: 70b4e7d748bc
Revises: 
Create Date: 2023-12-30 16:00:08.885541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70b4e7d748bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices_dev', 'device_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('devices_dev', 'created_on',new_column_name="date")
    op.alter_column('users_dev', 'created_on',new_column_name="date")
    op.add_column('insights_dev', sa.Column('job_id', sa.String(length=50), nullable=False))
    op.create_foreign_key(None, 'insights_dev', 'insight_jobs_dev', ['job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'insights_dev', type_='foreignkey')
    op.drop_column('insights_dev', 'job_id')
    op.alter_column('devices_dev', 'device_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('devices_dev', 'date',new_column_name="created_on")
    op.alter_column('users_dev', 'date',new_column_name="created_on")
    # ### end Alembic commands ###
