"""Add connection between insight and job

Revision ID: 97a2c5fc773c
Revises: c996cfde4bd5
Create Date: 2024-01-02 19:17:51.807278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97a2c5fc773c'
down_revision: Union[str, None] = 'c996cfde4bd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices_dev0', 'created_on', new_column_name='date')
    op.create_unique_constraint(None, 'users_dev0', ['user_id'])
    op.create_unique_constraint(None, 'users_dev0', ['user_name'])
    op.create_unique_constraint(None, 'devices_dev0', ['device_name'])
    op.create_unique_constraint(None, 'devices_dev0', ['device_id'])
    op.create_unique_constraint(None, 'insight_jobs_dev0', ['id'])
    op.create_unique_constraint(None, 'insight_engine_dev0', ['id'])
    op.create_unique_constraint(None, 'insights_dev0', ['id'])
    op.create_unique_constraint(None, 'media_dev0', ['media_id'])

    op.alter_column('devices_dev0', 'device_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('devices_dev0', 'device_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('devices_dev0', 'device_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('devices_dev0', 'owner_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    op.create_foreign_key(None, 'devices_dev0', 'users_dev0', ['owner_id'], ['user_id'])
    op.alter_column('insight_engine_dev0', 'id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('insight_engine_dev0', 'name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('insight_engine_dev0', 'input_source',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('insight_engine_dev0', 'input_queue_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('insight_engine_dev0', 'output_exchange_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('insight_engine_dev0', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    op.alter_column('insight_jobs_dev0', 'id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('insight_jobs_dev0', 'insight_engine_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('insight_jobs_dev0', 'media_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('insight_jobs_dev0', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('insight_jobs_dev0', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)

    op.create_foreign_key(None, 'insight_jobs_dev0', 'media_dev0', ['media_id'], ['media_id'])
    op.create_foreign_key(None, 'insight_jobs_dev0', 'insight_engine_dev0', ['insight_engine_id'], ['id'])
    op.add_column('insights_dev0', sa.Column('job_id', sa.String(length=50), nullable=False))
    op.alter_column('insights_dev0', 'id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('insights_dev0', 'insight_engine_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('insights_dev0', 'media_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('insights_dev0', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('insights_dev0', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    op.create_foreign_key(None, 'insights_dev0', 'insight_engine_dev0', ['insight_engine_id'], ['id'])
    op.create_foreign_key(None, 'insights_dev0', 'insight_jobs_dev0', ['job_id'], ['id'])
    op.create_foreign_key(None, 'insights_dev0', 'media_dev0', ['media_id'], ['media_id'])
    op.alter_column('media_dev0', 'media_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('media_dev0', 'media_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('media_dev0', 'media_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('media_dev0', 'media_size_bytes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('media_dev0', 'created_on',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('media_dev0', 'device_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('media_dev0', 'device_media_uri',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('media_dev0', 'upload_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('media_dev0', 'media_status_on_device',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('media_dev0', 'owner_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    op.create_foreign_key(None, 'media_dev0', 'devices_dev0', ['device_id'], ['device_id'])
    op.create_foreign_key(None, 'media_dev0', 'users_dev0', ['owner_id'], ['user_id'])
    op.alter_column('users_dev0', 'created_on', new_column_name='date')
    op.alter_column('users_dev0', 'user_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users_dev0', 'user_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users_dev0', 'password',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_dev0', 'date', new_column_name='created_on')
    op.drop_constraint(None, 'users_dev0', type_='unique')
    op.drop_constraint(None, 'users_dev0', type_='unique')
    op.alter_column('users_dev0', 'password',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('users_dev0', 'user_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users_dev0', 'user_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'media_dev0', type_='foreignkey')
    op.drop_constraint(None, 'media_dev0', type_='foreignkey')
    op.drop_constraint(None, 'media_dev0', type_='unique')
    op.alter_column('media_dev0', 'owner_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('media_dev0', 'media_status_on_device',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('media_dev0', 'upload_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('media_dev0', 'device_media_uri',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('media_dev0', 'device_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('media_dev0', 'created_on',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('media_dev0', 'media_size_bytes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('media_dev0', 'media_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('media_dev0', 'media_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('media_dev0', 'media_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'insights_dev0', type_='foreignkey')
    op.drop_constraint(None, 'insights_dev0', type_='foreignkey')
    op.drop_constraint(None, 'insights_dev0', type_='foreignkey')
    op.drop_constraint(None, 'insights_dev0', type_='unique')
    op.alter_column('insights_dev0', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('insights_dev0', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('insights_dev0', 'media_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('insights_dev0', 'insight_engine_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('insights_dev0', 'id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('insights_dev0', 'job_id')
    op.drop_constraint(None, 'insight_jobs_dev0', type_='foreignkey')
    op.drop_constraint(None, 'insight_jobs_dev0', type_='foreignkey')
    op.drop_constraint(None, 'insight_jobs_dev0', type_='unique')
    op.alter_column('insight_jobs_dev0', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('insight_jobs_dev0', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('insight_jobs_dev0', 'media_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('insight_jobs_dev0', 'insight_engine_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('insight_jobs_dev0', 'id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'insight_engine_dev0', type_='unique')
    op.alter_column('insight_engine_dev0', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('insight_engine_dev0', 'output_exchange_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('insight_engine_dev0', 'input_queue_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('insight_engine_dev0', 'input_source',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('insight_engine_dev0', 'name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('insight_engine_dev0', 'id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('devices_dev0', 'date', new_column_name='created_on')
    op.drop_constraint(None, 'devices_dev0', type_='foreignkey')
    op.drop_constraint(None, 'devices_dev0', type_='unique')
    op.drop_constraint(None, 'devices_dev0', type_='unique')
    op.alter_column('devices_dev0', 'owner_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('devices_dev0', 'device_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('devices_dev0', 'device_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('devices_dev0', 'device_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
