"""Add connection between insight and job

Revision ID: c996cfde4bd5
Revises: 
Create Date: 2023-12-31 19:17:56.670927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c996cfde4bd5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insights_dev0', sa.Column('job_id', sa.String(length=50), nullable=False))
    op.create_foreign_key(None, 'insights_dev0', 'insight_jobs_dev0', ['job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'insights_dev0', type_='foreignkey')
    op.drop_column('insights_dev0', 'job_id')
    # ### end Alembic commands ###
